name: Deploy to Edgeserver.io

on:
  push:
    branches:
      - "master"
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Edgeserver Upload
        uses: lvkdotsh/edgeserver-action@master
        with:
          app_id: "89661921279610880"
          server: https://api.edgeserver.io
          token: ${{ secrets.EDGE_TOKEN }}
          directory: src